Changing release body update

diff --git a/.github/workflows/project-release.yml b/.github/workflows/project-release.yml
--- a/.github/workflows/project-release.yml
+++ b/.github/workflows/project-release.yml
@@ -22,7 +22,8 @@ on:
 env:
   USER_PATH: project-main
   TEST_PATH: project-tests
-  
+  END_RESULT: ':warning: The checks for release `${{ needs.check_release.outputs.release_tag }}` did not complete properly.'
+  RUN_DETAIL: "See [run id ${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details."
 
 jobs:
   check_release:
@@ -107,12 +108,17 @@ jobs:
           user_cache: ${{ needs.check_release.outputs.user_cache }}
           test_cache: ${{ needs.check_release.outputs.test_cache }}
     
-      - name: "Compile user code"
+      - name: "Compile source code"
         working-directory: ${{ env.USER_PATH }}
         run: |
           mvn -ntp -DcompileOptionXlint=-Xlint:none -DcompileOptionXdoclint=-Xdoclint:none -Dmaven.compiler.showWarnings=false -DcompileOptionFail=false compile
+          
+          if [[ $? -ne 0 ]]; then
+            echo "::error ::Unable to compile your project source code."
+            exit 1
+          fi
 
-      - name: "Listing user code"
+      - name: "Listing source code"
         working-directory: ${{ env.USER_PATH }}
         run: |
           ls -ACGR target/classes
@@ -122,6 +128,11 @@ jobs:
         run: |
           mvn -ntp "-DcompileOptionXlint=-Xlint:none" "-DcompileOptionXdoclint=-Xdoclint:none" -Dmaven.compiler.showWarnings=false -DcompileOptionFail=false test-compile
 
+          if [[ $? -ne 0 ]]; then
+            echo "::error ::Unable to compile the project test code."
+            exit 1
+          fi
+          
       - name: "Listing test code"
         working-directory: ${{ env.USER_PATH }}
         run: |
@@ -151,11 +162,21 @@ jobs:
         run: |
           mvn -ntp -Dgroups="test${{ needs.check_release.outputs.project_num }}" test
 
+          if [[ $? -ne 0 ]]; then
+            echo "::error ::One or more tests for this project did not pass."
+            exit 1
+          fi
+
       - name: "Run previous project tests"
         working-directory: ${{ env.USER_PATH }}
         run: |
           mvn -ntp -Dgroups="past${{ needs.check_release.outputs.project_num }}" test
-          
+
+          if [[ $? -ne 0 ]]; then
+            echo "::error ::One or more tests for the past project did not pass."
+            exit 1
+          fi
+
       - name: "Run next project tests"
         working-directory: ${{ env.USER_PATH }}
         run: |
@@ -183,12 +204,17 @@ jobs:
           user_cache: ${{ needs.check_release.outputs.user_cache }}
           test_cache: ${{ needs.check_release.outputs.test_cache }}
     
-      - name: "Compile user code"
+      - name: "Compile source code"
         working-directory: ${{ env.USER_PATH }}
         run: |
           mvn -ntp "-DcompileOptionXlint=-Xlint:all,-processing" "-DcompileOptionXdoclint=-Xdoclint:none" -Dmaven.compiler.showWarnings=true -DcompileOptionFail=true clean compile
 
-      - name: "Listing user code"
+          if [[ $? -ne 0 ]]; then
+            echo "::error ::Unable to compile the project source code without warnings."
+            exit 1
+          fi
+
+      - name: "Listing source code"
         working-directory: ${{ env.USER_PATH }}
         run: |
           ls -ACGR target/classes
@@ -207,12 +233,17 @@ jobs:
           user_cache: ${{ needs.check_release.outputs.user_cache }}
           test_cache: ${{ needs.check_release.outputs.test_cache }}
     
-      - name: "Compile user code"
+      - name: "Compile source code"
         working-directory: ${{ env.USER_PATH }}
         run: |
           mvn -ntp "-DcompileOptionXlint=-Xlint:none" "-DcompileOptionXdoclint=-Xdoclint:all/private" -Dmaven.compiler.showWarnings=true -DcompileOptionFail=true clean compile
 
-      - name: "Listing user code"
+          if [[ $? -ne 0 ]]; then
+            echo "::error ::Unable to compile the project source code without Javadoc warnings."
+            exit 1
+          fi
+
+      - name: "Listing source code"
         working-directory: ${{ env.USER_PATH }}
         run: |
           ls -ACGR target/classes
@@ -247,43 +278,36 @@ jobs:
     needs: [check_release, check_compile, check_tests, check_source_warnings, check_javadoc_warnings, check_code_style]
     if: ${{ success() }}
     steps:
-      - name: "Update release"
+      - name: "Update status"
         run: |
-          BODY=":white_check_mark: The release \\\`${{ needs.check_release.outputs.release_tag }}\\\` passed all project ${{ needs.check_release.outputs.project_num }} checks. See [run id ${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details."
-          echo "$BODY"
-          echo "${{ github.event.release.id }}"
+          MESSAGE=':white_check_mark: The release `${{ needs.check_release.outputs.release_tag }}` passed all project ${{ needs.check_release.outputs.project_num }} checks.'
+          echo "END_RESULT=${MESSAGE}" >> $GITHUB_ENV
           
-          curl \
-            -X PATCH \
-            --header "Accept: application/vnd.github.v3+json" \
-            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
-            --header 'content-type: application/json' \
-            --url https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }} \
-            --data "{\"body\":\"World hello\"}"
-
   update_failure:
     name: "Update Failure"
     runs-on: ubuntu-latest
     needs: [check_release, check_compile, check_tests, check_source_warnings, check_javadoc_warnings, check_code_style]
-    if: ${{ failure() }}
-    env:
-      BODY: "Pending"
+    if: ${{ failure() || cancelled() }}
     steps:
       - name: "Update test success"
         if: ${{ needs.check_tests.result == 'success' }}
         run: |
-          BODY=":octocat: The release \\\`${{ needs.check_release.outputs.release_tag }}\\\` passed all project ${{ needs.check_release.outputs.project_num }} tests, but did not pass one or more of the other checks. See [run id ${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details."
-          BODY=":octocat: The release ${{ needs.check_release.outputs.release_tag }} passed all project ${{ needs.check_release.outputs.project_num }} tests, but did not pass one or more of the other checks. See [run id ${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details."
-          echo "$BODY"
-          echo "${{ github.event.release.id }}"
+          MESSAGE=':octocat: The release `${{ needs.check_release.outputs.release_tag }}` passed all project ${{ needs.check_release.outputs.project_num }} tests, but did not pass one or more of the other checks required for code review.'
+          echo "END_RESULT=${MESSAGE}" >> $GITHUB_ENV
 
       - name: "Update test failure"
         if: ${{ needs.check_tests.result != 'success' }}
         run: |
-          BODY='{"body":":x: The release `${{ needs.check_release.outputs.release_tag }}` did **NOT** pass all project ${{ needs.check_release.outputs.project_num }} tests. See [run id ${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details."}'
-      
-      - name: "Update release"
-        if: ${{ always() }}
+          MESSAGE=':x: The release `${{ needs.check_release.outputs.release_tag }}` did **NOT** pass all project ${{ needs.check_release.outputs.project_num }} tests.'
+          echo "END_RESULT=${MESSAGE}" >> $GITHUB_ENV
+  
+  update_release:
+    name: "Update Release"
+    runs-on: ubuntu-latest
+    needs: [update_success, update_failure]
+    if: ${{ always() }}
+    steps:
+      - name: "Update release body"
         run: |
           curl \
             -X PATCH \
@@ -291,7 +315,7 @@ jobs:
             --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
             --header 'content-type: application/json' \
             --url https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }} \
-            --data '{"body": "${{ env.BODY }}"}'
+            --data '{"body": "${{ env.END_RESULT }} ${{ env.RUN_DETAIL }}"}'
 
 # output action result
 # fix up updating release
