Debugging

diff --git a/.github/workflows/project-release.yml b/.github/workflows/project-release.yml
--- a/.github/workflows/project-release.yml
+++ b/.github/workflows/project-release.yml
@@ -234,7 +234,12 @@ jobs:
       - name: "Check extra main methods"
         working-directory: ${{ env.USER_PATH }}/src/main/java
         run: |
-          grep -rnoiE --exclude=Driver.java \\s*public\\s+static\\s+void\\s+main\\s*\\( .
+          grep -rnoiE --exclude=Driver.java '\s*public\s+static\s+void\s+main\s*\('
+          
+          if [[ $? -ne 0 ]]; then
+            echo "::error ::Except for Driver.java, you should delete old main methods from your code."
+            exit 1
+          fi
 
   update_success:
     name: "Update Success"
@@ -261,6 +266,8 @@ jobs:
     runs-on: ubuntu-latest
     needs: [check_release, check_compile, check_tests, check_source_warnings, check_javadoc_warnings, check_code_style]
     if: ${{ failure() }}
+    env:
+      BODY: "Pending"
     steps:
       - name: "Update test success"
         if: ${{ needs.check_tests.result == 'success' }}
@@ -269,26 +276,21 @@ jobs:
           BODY=":octocat: The release ${{ needs.check_release.outputs.release_tag }} passed all project ${{ needs.check_release.outputs.project_num }} tests, but did not pass one or more of the other checks. See [run id ${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details."
           echo "$BODY"
           echo "${{ github.event.release.id }}"
-          
-          curl \
-            -X PATCH \
-            --header "Accept: application/vnd.github.v3+json" \
-            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
-            --header 'content-type: application/json' \
-            --url https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }} \
-            --data "{\"body\":\"${BODY}\"}"
 
       - name: "Update test failure"
         if: ${{ needs.check_tests.result != 'success' }}
         run: |
           BODY='{"body":":x: The release `${{ needs.check_release.outputs.release_tag }}` did **NOT** pass all project ${{ needs.check_release.outputs.project_num }} tests. See [run id ${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details."}'
-          
+      
+      - name: "Update release"
+        if: ${{ always() }}
+        run: |
           curl \
             -X PATCH \
             --header "Accept: application/vnd.github.v3+json" \
             --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
             --header 'content-type: application/json' \
             --url https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }} \
-            --data ${BODY}
+            --data '${{ env.BODY }}'
 
 # https://docs.github.com/en/rest/reference/releases#update-a-release
