Updating testing

diff --git a/.github/workflows/project-release.yml b/.github/workflows/project-release.yml
--- a/.github/workflows/project-release.yml
+++ b/.github/workflows/project-release.yml
@@ -132,8 +132,29 @@ jobs:
     runs-on: ubuntu-latest
     needs: [check_release, check_compile]
     steps:
-      - name: "Hello world"
-        run: echo "Hello world"
+      - name: "Recompile code"
+        run: |
+          mvn -ntp -DcompileOptionXlint=-Xlint:none -DcompileOptionXdoclint=-Xdoclint:none -Dmaven.compiler.showWarnings=false -DcompileOptionFail=false clean compile test-compile
+      
+      - name: "Run current project tests"
+        run: |
+          mvn -ntp -Dgroups="test${{ needs.check_release.outputs.project_num }}" test
+
+      - name: "Run previous project tests"
+        run: |
+          mvn -ntp -Dgroups="past${{ needs.check_release.outputs.project_num }}" test
+          
+      - name: "Run next project tests"
+        run: |
+          mvn -ntp -Dgroups="next${{ needs.check_release.outputs.project_num }}" test
+          
+          if [[ $? -eq 0 ]]; then
+            echo "These tests are expected to fail!"
+            exit 0
+          else
+            echo "::error ::The tests for the next project should not yet pass! You must work on the next project in a separate branch from your current project."
+            exit 1
+          fi
 
   check_source_warnings:
     name: "Code Warnings"
@@ -230,7 +251,7 @@ jobs:
             --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
             --header 'content-type: application/json' \
             --url https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }} \
-            --data "{\"body\":\"${BODY}\"}"
+            --data "{\"body\":\"Hello world\"}"
 
       - name: "Update test failure"
         if: ${{ needs.check_tests.result != 'success' }}
