Testing setting outputs

diff --git a/.github/workflows/project-release.yml b/.github/workflows/project-release.yml
--- a/.github/workflows/project-release.yml
+++ b/.github/workflows/project-release.yml
@@ -271,6 +271,16 @@ jobs:
             exit 1
           fi
 
+      - name: "Check extra TODO comments"
+        working-directory: ${{ env.USER_PATH }}/src/main/java
+        run: |
+          grep -rnoiE '(//|\*)?\s*TODO.*$'
+          
+          if [[ $? -ne 1 ]]; then
+            echo "::error ::You should delete old TODO comments from your code."
+            exit 1
+          fi
+
   update_success:
     name: "Update Success"
     runs-on: ubuntu-latest
@@ -289,9 +299,12 @@ jobs:
     needs: [check_release, check_compile, check_tests, check_source_warnings, check_javadoc_warnings, check_code_style]
     if: ${{ failure() || cancelled() }}
     steps:
+      - run: echo "::set-output name=potato::pocket"
+      
       - name: "Update test success"
         if: ${{ needs.check_tests.result == 'success' }}
         run: |
+          echo "::set-output name=why::please"
           MESSAGE='Eligibility: :white_check_mark: Project Test, :x: Project Review%0A:octocat: The release `${{ needs.check_release.outputs.release_tag }}` passed all project ${{ needs.check_release.outputs.project_num }} tests, but did not pass one or more of the other checks required for code review. This release may be used to request a project test grade only.'
           echo "::set-output name=message::${MESSAGE}"
           echo "${MESSAGE}"
@@ -299,8 +312,9 @@ jobs:
       - name: "Update test failure"
         if: ${{ needs.check_tests.result != 'success' }}
         run: |
+          echo "::set-output name=hello::hello"
           MESSAGE='Eligibility: :x: Project Test, :x: Project Review%0A:warning: The release `${{ needs.check_release.outputs.release_tag }}` did **NOT** pass all project ${{ needs.check_release.outputs.project_num }} tests. This release may not be used to request a grade or code review.'
-          echo "::set-output name=check_status::hello"
+          echo "::set-output name=world::world"
           echo "${MESSAGE}"
   
   update_release:
